import React from "react";
import { Clipboard, FileText, ShieldCheck, Trash2 } from "lucide-react";
import { clearEvidenceItems, EVIDENCE_CHANGED_EVENT, readEvidenceItems, removeEvidenceItem } from "../lib/evidence";
import type { AdminConfig, EvidenceItem, Language, UserSession } from "../types";

type EvidenceWorkbenchProps = {
  config: AdminConfig;
  language: Language;
  session: UserSession | null;
};

const copy = {
  en: {
    eyebrow: "Evidence Export",
    title: "Sanitized UAT evidence package",
    lead: "Evidence copied from workbenches is stored locally in this browser and can be bundled for UAT records.",
    itemCount: "Items",
    successCount: "Successful",
    traceCount: "Trace IDs",
    copyPackage: "Copy Package",
    clearAll: "Clear All",
    remove: "Remove",
    empty: "No saved evidence yet. Use Copy Evidence in a workbench to add sanitized snippets here.",
    type: "Type",
    evidenceTitle: "Title",
    generated: "Generated",
    trace: "Trace",
    status: "Status",
    action: "Action",
    copied: "Evidence package copied",
    packagePolicy:
      "The package contains sanitized JSON snippets already generated by the workbenches. API keys, uploaded files, request payloads, response payloads, and raw failure payloads are excluded by policy.",
    operator: "Operator",
    environment: "Environment"
  },
  zh: {
    eyebrow: "证据导出",
    title: "脱敏 UAT 证据包",
    lead: "各工作台复制出的脱敏证据会暂存在当前浏览器，可在这里汇总成 UAT 记录包。",
    itemCount: "证据数",
    successCount: "成功项",
    traceCount: "Trace 数",
    copyPackage: "复制整包",
    clearAll: "清空",
    remove: "移除",
    empty: "暂无已保存证据。请在具体工作台点击“复制证据”后再到这里汇总。",
    type: "类型",
    evidenceTitle: "标题",
    generated: "生成时间",
    trace: "Trace",
    status: "状态",
    action: "操作",
    copied: "证据包已复制",
    packagePolicy:
      "证据包只包含各工作台生成的脱敏 JSON 片段。按照策略排除 API Key、上传文件、请求原文、响应原文和失败行 raw payload。",
    operator: "操作员",
    environment: "环境"
  }
};

function c(language: Language, key: keyof typeof copy.en): string {
  return copy[language][key];
}

function display(value: unknown): string {
  if (value === null || value === undefined || value === "") {
    return "-";
  }
  return String(value);
}

function formatDate(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }
  return date.toLocaleString();
}

function buildPackage(items: EvidenceItem[], config: AdminConfig, session: UserSession | null) {
  return {
    evidence_package_type: "H_UMDG_ADMIN_UI_ALPHA_UAT_PACKAGE",
    generated_at: new Date().toISOString(),
    item_count: items.length,
    environment: {
      name: config.environmentName,
      candidate_version: config.candidateVersion,
      api_base_url: config.apiBaseUrl
    },
    operator: session
      ? {
          username: session.username,
          display_name: session.displayName,
          role: session.role,
          auth_model: session.authModel ?? "local_preview"
        }
      : null,
    policy: {
      api_keys_included: false,
      raw_files_included: false,
      raw_request_payloads_included: false,
      raw_response_payloads_included: false,
      raw_failure_payloads_included: false
    },
    items: items.map((item) => item.payload)
  };
}

export function EvidenceWorkbench({ config, language, session }: EvidenceWorkbenchProps) {
  const [items, setItems] = React.useState<EvidenceItem[]>(() => readEvidenceItems());
  const [notice, setNotice] = React.useState<string | null>(null);

  const refresh = React.useCallback(() => {
    setItems(readEvidenceItems());
  }, []);

  React.useEffect(() => {
    window.addEventListener(EVIDENCE_CHANGED_EVENT, refresh);
    window.addEventListener("storage", refresh);
    return () => {
      window.removeEventListener(EVIDENCE_CHANGED_EVENT, refresh);
      window.removeEventListener("storage", refresh);
    };
  }, [refresh]);

  const successCount = items.filter((item) => item.ok === true).length;
  const traceCount = new Set(items.map((item) => item.trace_id).filter(Boolean)).size;

  const copyPackage = async () => {
    const payload = JSON.stringify(buildPackage(items, config, session), null, 2);
    await navigator.clipboard.writeText(payload);
    setNotice(c(language, "copied"));
  };

  const removeItem = (id: string) => {
    removeEvidenceItem(id);
    refresh();
  };

  const clearAll = () => {
    clearEvidenceItems();
    refresh();
  };

  return (
    <section className="panel evidence-panel" aria-labelledby="evidence-heading">
      <div className="panel-heading">
        <div>
          <p className="eyebrow">{c(language, "eyebrow")}</p>
          <h2 id="evidence-heading">{c(language, "title")}</h2>
        </div>
        <FileText size={20} />
      </div>

      <p className="workflow-description">{c(language, "lead")}</p>

      {notice ? <div className="notice-line notice-line-ok">{notice}</div> : null}

      <div className="counter-grid evidence-counter-grid">
        <div>
          <span>{c(language, "itemCount")}</span>
          <strong>{items.length}</strong>
        </div>
        <div>
          <span>{c(language, "successCount")}</span>
          <strong>{successCount}</strong>
        </div>
        <div>
          <span>{c(language, "traceCount")}</span>
          <strong>{traceCount}</strong>
        </div>
      </div>

      <div className="section-toolbar">
        <div className="transcode-heading">
          <ShieldCheck size={17} />
          <strong>{c(language, "packagePolicy")}</strong>
        </div>
        <div className="button-row">
          <button className="tool-button" type="button" disabled={!items.length} onClick={copyPackage}>
            <Clipboard size={17} />
            {c(language, "copyPackage")}
          </button>
          <button className="tool-button" type="button" disabled={!items.length} onClick={clearAll}>
            <Trash2 size={17} />
            {c(language, "clearAll")}
          </button>
        </div>
      </div>

      <dl className="task-detail-grid evidence-context-grid">
        <div>
          <dt>{c(language, "environment")}</dt>
          <dd>
            {config.environmentName} / {config.candidateVersion}
          </dd>
        </div>
        <div>
          <dt>{c(language, "operator")}</dt>
          <dd>{session ? `${session.displayName} / ${session.role}` : "-"}</dd>
        </div>
      </dl>

      {items.length ? (
        <div className="data-table evidence-table" role="table" aria-label="Saved evidence">
          <div role="row">
            <span role="columnheader">{c(language, "type")}</span>
            <span role="columnheader">{c(language, "evidenceTitle")}</span>
            <span role="columnheader">{c(language, "generated")}</span>
            <span role="columnheader">{c(language, "trace")}</span>
            <span role="columnheader">{c(language, "status")}</span>
            <span role="columnheader">{c(language, "action")}</span>
          </div>
          {items.map((item) => (
            <div role="row" key={item.id}>
              <span>{display(item.evidence_type)}</span>
              <span>{display(item.title)}</span>
              <span>{formatDate(item.generated_at)}</span>
              <span>{display(item.trace_id)}</span>
              <span>{item.ok === undefined ? "-" : item.ok ? "OK" : `HTTP ${display(item.http_status)}`}</span>
              <span>
                <button className="table-action" type="button" onClick={() => removeItem(item.id)}>
                  {c(language, "remove")}
                </button>
              </span>
            </div>
          ))}
        </div>
      ) : (
        <div className="empty-state">{c(language, "empty")}</div>
      )}
    </section>
  );
}
